/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DoubleClickPreviewPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  popupStyle: "modal",
  popupWidth: 650,
  popupHeight: 500
};
var DoubleClickPreviewPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.popoverEl = null;
    this.popoverComponent = null;
    this.clickHref = null;
    this.clickTime = 0;
    this.clickSource = "";
    this.clickRect = null;
    this.navTimer = null;
    this.boundHandler = null;
    this.touchTimer = null;
    this.touchHref = null;
    this.touchRect = null;
    this.touchPreventClick = false;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new SettingTab(this.app, this));
    this.isTouchDevice = window.matchMedia("(pointer: coarse)").matches;
    this.boundHandler = (evt) => this.onClick(evt);
    document.addEventListener("click", this.boundHandler, true);
    if (this.isTouchDevice) {
      this.registerDomEvent(
        document,
        "touchstart",
        (evt) => this.onTouchStart(evt)
      );
      this.registerDomEvent(
        document,
        "touchend",
        () => this.onTouchEnd()
      );
      this.registerDomEvent(
        document,
        "touchmove",
        () => this.onTouchMove()
      );
      this.registerDomEvent(
        document,
        "contextmenu",
        (evt) => this.onTouchContextMenu(evt)
      );
    }
    this.register(() => {
      if (this.boundHandler) {
        document.removeEventListener("click", this.boundHandler, true);
      }
      this.clearTimer();
    });
  }
  onunload() {
    this.closePopover();
  }
  onTouchStart(evt) {
    const target = evt.target;
    if (target.closest(".link-preview-popover, .modal-container"))
      return;
    const linkEl = target.closest(
      "a.internal-link, a.external-link, .cm-hmd-internal-link, .cm-url, [data-href]"
    );
    if (!linkEl)
      return;
    const href = this.getHref(linkEl);
    if (!href)
      return;
    this.touchHref = href;
    this.touchRect = linkEl.getBoundingClientRect();
    this.touchTimer = window.setTimeout(() => {
      this.touchTimer = null;
      this.touchPreventClick = true;
      if (this.touchHref && this.touchRect) {
        this.openPreview(this.touchHref, this.touchRect);
      }
    }, 500);
  }
  onTouchEnd() {
    if (this.touchTimer !== null) {
      clearTimeout(this.touchTimer);
      this.touchTimer = null;
    }
  }
  onTouchMove() {
    if (this.touchTimer !== null) {
      clearTimeout(this.touchTimer);
      this.touchTimer = null;
    }
  }
  onTouchContextMenu(evt) {
    if (this.touchTimer !== null) {
      clearTimeout(this.touchTimer);
      this.touchTimer = null;
      this.touchPreventClick = true;
      if (this.touchHref && this.touchRect) {
        this.openPreview(this.touchHref, this.touchRect);
      }
      evt.preventDefault();
    } else if (this.touchPreventClick) {
      evt.preventDefault();
      this.touchPreventClick = false;
    }
  }
  clearTimer() {
    if (this.navTimer !== null) {
      clearTimeout(this.navTimer);
      this.navTimer = null;
    }
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  getSourcePath() {
    var _a, _b;
    const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    return (_b = (_a = view == null ? void 0 : view.file) == null ? void 0 : _a.path) != null ? _b : "";
  }
  getHref(el) {
    let href = el.getAttribute("data-href");
    if (href)
      return href;
    href = el.getAttribute("href");
    if (href)
      return href;
    if (el.classList.contains("cm-url")) {
      const text = el.textContent || "";
      href = text.replace(/^\(/, "").replace(/\)$/, "");
      if (href)
        return href;
    }
    return null;
  }
  onClick(evt) {
    const target = evt.target;
    if (target.closest(".link-preview-popover, .modal-container"))
      return;
    const linkEl = target.closest(
      "a.internal-link, a.external-link, .cm-hmd-internal-link, .cm-url, [data-href]"
    );
    if (!linkEl) {
      this.clickHref = null;
      this.clearTimer();
      return;
    }
    const href = this.getHref(linkEl);
    if (!href) {
      this.clickHref = null;
      this.clearTimer();
      return;
    }
    const now = Date.now();
    if (this.clickHref && now - this.clickTime < 650) {
      this.clearTimer();
      this.clickHref = null;
      evt.preventDefault();
      evt.stopPropagation();
      const rect = linkEl.getBoundingClientRect();
      this.openPreview(href, rect);
      return;
    }
    this.clickHref = href;
    this.clickTime = now;
    this.clickSource = this.getSourcePath();
    this.clickRect = linkEl.getBoundingClientRect();
    evt.preventDefault();
    evt.stopPropagation();
    this.clearTimer();
    this.navTimer = window.setTimeout(() => {
      this.navTimer = null;
      this.clickHref = null;
      this.navigateTo(href, this.clickSource);
    }, 650);
  }
  navigateTo(href, sourcePath) {
    if (href.startsWith("http://") || href.startsWith("https://")) {
      window.open(href);
      return;
    }
    const file = this.app.metadataCache.getFirstLinkpathDest(href, sourcePath);
    if (file) {
      const leaf = this.app.workspace.getLeaf(false);
      if (leaf) {
        leaf.openFile(file);
        return;
      }
    }
    try {
      this.app.workspace.openLinkText(href, sourcePath);
    } catch (e) {
    }
  }
  async openPreview(href, rect) {
    if (href.startsWith("http://") || href.startsWith("https://")) {
      this.showExternal(href, rect);
    } else {
      await this.showInternal(href, rect);
    }
  }
  renderProperties(container, file) {
    if (!file)
      return;
    const cache = this.app.metadataCache.getFileCache(file);
    if (!(cache == null ? void 0 : cache.frontmatter))
      return;
    const details = container.createEl("details", {
      cls: "link-preview-properties"
    });
    const summary = details.createEl("summary", {
      cls: "link-preview-properties-header",
      text: "\u6587\u6863\u5C5E\u6027"
    });
    for (const [k, v] of Object.entries(cache.frontmatter)) {
      if (k === "position" || k === "sticky")
        continue;
      const row = details.createDiv("link-preview-prop-row");
      row.createSpan({ text: k, cls: "link-preview-prop-key" });
      row.createSpan({ text: String(v), cls: "link-preview-prop-value" });
    }
  }
  async showInternal(href, rect) {
    const sourcePath = this.getSourcePath();
    const file = this.app.metadataCache.getFirstLinkpathDest(href, sourcePath);
    if (!file)
      return;
    const content = await this.app.vault.cachedRead(file);
    if (this.settings.popupStyle === "modal") {
      new PreviewModal(this.app, file.name, content, file.path, file, this).open();
    } else {
      this.showPopover(content, file.path, file.name, file, rect);
    }
  }
  async showExternal(url, rect) {
    const content = `[${url}](${url})`;
    if (this.settings.popupStyle === "modal") {
      new PreviewModal(this.app, "External Link", content, "", null, this).open();
    } else {
      this.showPopover(content, "", url, null, rect);
    }
  }
  showPopover(content, sourcePath, title, file, rect) {
    this.closePopover();
    const el = document.body.createDiv("link-preview-popover");
    el.style.width = `${this.settings.popupWidth}px`;
    el.style.maxHeight = `${this.settings.popupHeight}px`;
    const header = el.createDiv("link-preview-popover-header");
    header.createSpan({ text: title });
    const close = header.createEl("button", {
      cls: "link-preview-popover-close",
      text: "\xD7"
    });
    close.addEventListener("click", () => this.closePopover());
    const body = el.createDiv("link-preview-popover-content");
    this.renderProperties(body, file);
    const cmp = new import_obsidian.Component();
    cmp.load();
    import_obsidian.MarkdownRenderer.render(this.app, content, body, sourcePath, cmp);
    this.popoverComponent = cmp;
    this.popoverEl = el;
    document.body.appendChild(el);
    const sz = el.getBoundingClientRect();
    let top = rect.bottom + 6;
    let left = Math.max(6, rect.left);
    if (top + sz.height > window.innerHeight) {
      top = Math.max(6, rect.top - sz.height - 6);
    }
    if (left + sz.width > window.innerWidth) {
      left = Math.max(6, window.innerWidth - sz.width - 6);
    }
    el.style.top = `${top}px`;
    el.style.left = `${left}px`;
    requestAnimationFrame(() => el.classList.add("is-visible"));
    this.makeDraggable(el, el);
    const closeHandler = (e) => {
      if (!el.contains(e.target)) {
        this.closePopover();
        document.removeEventListener("click", closeHandler);
      }
    };
    setTimeout(() => document.addEventListener("click", closeHandler), 0);
  }
  makeDraggable(handle, target) {
    let startX = 0, startY = 0, origX = 0, origY = 0;
    const onStart = (e) => {
      if (e.target.closest("button, a, input, textarea"))
        return;
      startX = e.clientX;
      startY = e.clientY;
      origX = parseInt(target.style.left) || 0;
      origY = parseInt(target.style.top) || 0;
      target.classList.add("is-dragging");
      document.addEventListener("mousemove", onMove);
      document.addEventListener("mouseup", onEnd);
      e.preventDefault();
    };
    const onMove = (e) => {
      target.style.left = `${origX + e.clientX - startX}px`;
      target.style.top = `${origY + e.clientY - startY}px`;
    };
    const onEnd = () => {
      target.classList.remove("is-dragging");
      document.removeEventListener("mousemove", onMove);
      document.removeEventListener("mouseup", onEnd);
    };
    handle.addEventListener("mousedown", onStart);
  }
  closePopover() {
    if (this.popoverComponent) {
      this.popoverComponent.unload();
      this.popoverComponent = null;
    }
    if (this.popoverEl) {
      this.popoverEl.remove();
      this.popoverEl = null;
    }
  }
};
var PreviewModal = class extends import_obsidian.Modal {
  constructor(app, title, content, sourcePath, file, plugin) {
    super(app);
    this.title = title;
    this.content = content;
    this.sourcePath = sourcePath;
    this.file = file;
    this.plugin = plugin;
  }
  onOpen() {
    this.modalEl.style.width = `${this.plugin.settings.popupWidth}px`;
    this.modalEl.style.maxHeight = `${this.plugin.settings.popupHeight}px`;
    this.contentEl.empty();
    const titleEl = this.contentEl.createDiv("link-preview-modal-title");
    titleEl.setText(this.title);
    this.makeDraggable(this.modalEl, this.modalEl);
    const preview = this.contentEl.createDiv("link-preview-modal-content");
    this.plugin.renderProperties(preview, this.file);
    import_obsidian.MarkdownRenderer.render(this.app, this.content, preview, this.sourcePath, this);
  }
  onClose() {
    this.contentEl.empty();
  }
  makeDraggable(handle, target) {
    let startX = 0, startY = 0, origX = 0, origY = 0;
    const onStart = (e) => {
      if (e.target.closest("button, a, input, textarea"))
        return;
      startX = e.clientX;
      startY = e.clientY;
      origX = parseInt(target.style.left) || 0;
      origY = parseInt(target.style.top) || 0;
      target.style.removeProperty("margin");
      target.classList.add("is-dragging");
      document.addEventListener("mousemove", onMove);
      document.addEventListener("mouseup", onEnd);
      e.preventDefault();
    };
    const onMove = (e) => {
      target.style.left = `${origX + e.clientX - startX}px`;
      target.style.top = `${origY + e.clientY - startY}px`;
    };
    const onEnd = () => {
      target.classList.remove("is-dragging");
      document.removeEventListener("mousemove", onMove);
      document.removeEventListener("mouseup", onEnd);
    };
    handle.addEventListener("mousedown", onStart);
  }
};
var SettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("\u5F39\u7A97\u4F4D\u7F6E").setDesc("\u9009\u62E9\u9884\u89C8\u7684\u663E\u793A\u4F4D\u7F6E").addDropdown(
      (d) => d.addOption("popover", "\u6D6E\u7A97\uFF08\u94FE\u63A5\u9644\u8FD1\uFF09").addOption("modal", "\u6A21\u6001\u6846\uFF08\u5C4F\u5E55\u5C45\u4E2D\uFF09").setValue(this.plugin.settings.popupStyle).onChange(async (v) => {
        this.plugin.settings.popupStyle = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u5F39\u7A97\u5BBD\u5EA6").setDesc("\u5BBD\u5EA6\uFF08\u50CF\u7D20\uFF09").addText(
      (t) => t.setPlaceholder("650").setValue(String(this.plugin.settings.popupWidth)).onChange(async (v) => {
        const n = parseInt(v);
        if (!isNaN(n) && n > 0) {
          this.plugin.settings.popupWidth = n;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u5F39\u7A97\u6700\u5927\u9AD8\u5EA6").setDesc("\u6700\u5927\u9AD8\u5EA6\uFF08\u50CF\u7D20\uFF09").addText(
      (t) => t.setPlaceholder("500").setValue(String(this.plugin.settings.popupHeight)).onChange(async (v) => {
        const n = parseInt(v);
        if (!isNaN(n) && n > 0) {
          this.plugin.settings.popupHeight = n;
          await this.plugin.saveSettings();
        }
      })
    );
  }
};
